CREATE TABLE IF NOT EXISTS public.media_assets (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  entity TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  public_id TEXT NOT NULL,
  resource_type TEXT NOT NULL CHECK (resource_type IN ('image', 'video', 'raw')),
  secure_url TEXT NOT NULL,
  width INTEGER,
  height INTEGER,
  bytes BIGINT NOT NULL CHECK (bytes >= 0),
  format TEXT NOT NULL,
  duration NUMERIC,
  sort_order INTEGER NOT NULL DEFAULT 0,
  alt_text TEXT NOT NULL DEFAULT '',
  source_bucket TEXT,
  source_path TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (entity, entity_id, public_id)
);

CREATE INDEX IF NOT EXISTS idx_media_assets_entity_order
  ON public.media_assets (entity, entity_id, sort_order);

ALTER TABLE public.media_assets ENABLE ROW LEVEL SECURITY;
DROP POLICY IF EXISTS "Public can read media references" ON public.media_assets;
CREATE POLICY "Public can read media references"
  ON public.media_assets FOR SELECT
  USING (true);

REVOKE INSERT, UPDATE, DELETE ON public.media_assets FROM anon, authenticated;
GRANT SELECT ON public.media_assets TO anon, authenticated;
GRANT ALL ON public.media_assets TO service_role;

CREATE TABLE IF NOT EXISTS public.media_upload_rate_limits (
  ip_hash TEXT NOT NULL,
  window_start TIMESTAMPTZ NOT NULL,
  request_count INTEGER NOT NULL CHECK (request_count > 0),
  PRIMARY KEY (ip_hash, window_start)
);

REVOKE ALL ON public.media_upload_rate_limits FROM anon, authenticated;
GRANT ALL ON public.media_upload_rate_limits TO service_role;

CREATE OR REPLACE FUNCTION public.consume_media_upload_limit(
  p_ip_hash TEXT,
  p_max_requests INTEGER,
  p_window_seconds INTEGER
)
RETURNS BOOLEAN
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_window_start TIMESTAMPTZ;
  v_count INTEGER;
BEGIN
  IF p_ip_hash IS NULL OR length(p_ip_hash) <> 64
    OR p_max_requests < 1 OR p_window_seconds < 1 THEN
    RAISE EXCEPTION 'Invalid upload rate-limit parameters';
  END IF;

  v_window_start := to_timestamp(
    floor(extract(epoch FROM clock_timestamp()) / p_window_seconds) * p_window_seconds
  );

  INSERT INTO public.media_upload_rate_limits (ip_hash, window_start, request_count)
  VALUES (p_ip_hash, v_window_start, 1)
  ON CONFLICT (ip_hash, window_start) DO UPDATE
    SET request_count = public.media_upload_rate_limits.request_count + 1
    WHERE public.media_upload_rate_limits.request_count < p_max_requests
  RETURNING request_count INTO v_count;

  RETURN FOUND;
END;
$$;

REVOKE ALL ON FUNCTION public.consume_media_upload_limit(TEXT, INTEGER, INTEGER) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.consume_media_upload_limit(TEXT, INTEGER, INTEGER) TO service_role;

CREATE TABLE IF NOT EXISTS public.media_migration_map (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  old_url TEXT NOT NULL,
  new_public_id TEXT NOT NULL,
  new_url TEXT NOT NULL,
  entity TEXT NOT NULL,
  entity_id TEXT NOT NULL,
  source_bucket TEXT NOT NULL,
  source_path TEXT NOT NULL,
  migrated_at TIMESTAMPTZ NOT NULL DEFAULT now(),
  UNIQUE (old_url, entity, entity_id)
);

CREATE INDEX IF NOT EXISTS idx_media_migration_map_new_public_id
  ON public.media_migration_map (new_public_id);

ALTER TABLE public.media_migration_map ENABLE ROW LEVEL SECURITY;
REVOKE ALL ON public.media_migration_map FROM anon, authenticated;
GRANT ALL ON public.media_migration_map TO service_role;

CREATE OR REPLACE FUNCTION public.apply_media_migration_batch(
  p_changes JSONB,
  p_rollback BOOLEAN DEFAULT FALSE
)
RETURNS INTEGER
LANGUAGE plpgsql
SECURITY DEFINER
SET search_path = public
AS $$
DECLARE
  v_change JSONB;
  v_table TEXT;
  v_column TEXT;
  v_row_id TEXT;
  v_expected JSONB;
  v_target JSONB;
  v_count INTEGER := 0;
  v_rows INTEGER;
  v_item JSONB;
BEGIN
  IF jsonb_typeof(p_changes) <> 'array' THEN
    RAISE EXCEPTION 'Media migration changes must be an array';
  END IF;

  FOR v_change IN SELECT value FROM jsonb_array_elements(p_changes)
  LOOP
    v_table := v_change->>'table_name';
    v_column := v_change->>'column_name';
    v_row_id := v_change->>'row_id';

    IF v_table IS NULL OR v_column IS NULL OR v_row_id IS NULL
      OR NOT EXISTS (
        SELECT 1
        FROM information_schema.columns
        WHERE table_schema = 'public'
          AND table_name = v_table
          AND column_name IN (v_column, 'id')
        GROUP BY table_name
        HAVING count(DISTINCT column_name) = 2
      ) THEN
      RAISE EXCEPTION 'Invalid media migration target: %.%', v_table, v_column;
    END IF;

    v_expected := CASE WHEN p_rollback THEN v_change->'new_value' ELSE v_change->'old_value' END;
    v_target := CASE WHEN p_rollback THEN v_change->'old_value' ELSE v_change->'new_value' END;

    EXECUTE format(
      'UPDATE public.%1$I AS target
       SET %2$I = (jsonb_populate_record(NULL::public.%1$I, jsonb_build_object(%3$L, $1))).%2$I
       WHERE target.id::text = $2 AND to_jsonb(target.%2$I) = $3',
      v_table,
      v_column,
      v_column
    )
    USING v_target, v_row_id, v_expected;

    GET DIAGNOSTICS v_rows = ROW_COUNT;
    IF v_rows <> 1 THEN
      RAISE EXCEPTION 'Media migration conflict at %.% row %', v_table, v_column, v_row_id;
    END IF;
    v_count := v_count + 1;

    IF p_rollback THEN
      FOR v_item IN SELECT value FROM jsonb_array_elements(COALESCE(v_change->'maps', '[]'::jsonb))
      LOOP
        DELETE FROM public.media_migration_map
        WHERE old_url = v_item->>'old_url'
          AND entity = v_item->>'entity'
          AND entity_id = v_item->>'entity_id';
      END LOOP;

      FOR v_item IN SELECT value FROM jsonb_array_elements(COALESCE(v_change->'assets', '[]'::jsonb))
      LOOP
        DELETE FROM public.media_assets
        WHERE entity = v_item->>'entity'
          AND entity_id = v_item->>'entity_id'
          AND public_id = v_item->>'public_id'
          AND source_bucket = v_item->>'source_bucket'
          AND source_path = v_item->>'source_path';
      END LOOP;
    ELSE
      FOR v_item IN SELECT value FROM jsonb_array_elements(COALESCE(v_change->'maps', '[]'::jsonb))
      LOOP
        INSERT INTO public.media_migration_map (
          old_url,
          new_public_id,
          new_url,
          entity,
          entity_id,
          source_bucket,
          source_path
        )
        VALUES (
          v_item->>'old_url',
          v_item->>'new_public_id',
          v_item->>'new_url',
          v_item->>'entity',
          v_item->>'entity_id',
          v_item->>'source_bucket',
          v_item->>'source_path'
        )
        ON CONFLICT (old_url, entity, entity_id) DO UPDATE
          SET new_public_id = EXCLUDED.new_public_id,
              new_url = EXCLUDED.new_url,
              source_bucket = EXCLUDED.source_bucket,
              source_path = EXCLUDED.source_path,
              migrated_at = now();
      END LOOP;

      FOR v_item IN SELECT value FROM jsonb_array_elements(COALESCE(v_change->'assets', '[]'::jsonb))
      LOOP
        INSERT INTO public.media_assets (
          entity,
          entity_id,
          public_id,
          resource_type,
          secure_url,
          width,
          height,
          bytes,
          format,
          duration,
          sort_order,
          alt_text,
          source_bucket,
          source_path
        )
        VALUES (
          v_item->>'entity',
          v_item->>'entity_id',
          v_item->>'public_id',
          v_item->>'resource_type',
          v_item->>'secure_url',
          NULLIF(v_item->>'width', '')::INTEGER,
          NULLIF(v_item->>'height', '')::INTEGER,
          (v_item->>'bytes')::BIGINT,
          v_item->>'format',
          NULLIF(v_item->>'duration', '')::NUMERIC,
          COALESCE(NULLIF(v_item->>'sort_order', '')::INTEGER, 0),
          COALESCE(v_item->>'alt_text', ''),
          v_item->>'source_bucket',
          v_item->>'source_path'
        )
        ON CONFLICT (entity, entity_id, public_id) DO UPDATE
          SET resource_type = EXCLUDED.resource_type,
              secure_url = EXCLUDED.secure_url,
              width = EXCLUDED.width,
              height = EXCLUDED.height,
              bytes = EXCLUDED.bytes,
              format = EXCLUDED.format,
              duration = EXCLUDED.duration,
              sort_order = EXCLUDED.sort_order,
              alt_text = EXCLUDED.alt_text,
              source_bucket = EXCLUDED.source_bucket,
              source_path = EXCLUDED.source_path;
      END LOOP;
    END IF;
  END LOOP;

  RETURN v_count;
END;
$$;

REVOKE ALL ON FUNCTION public.apply_media_migration_batch(JSONB, BOOLEAN) FROM PUBLIC, anon, authenticated;
GRANT EXECUTE ON FUNCTION public.apply_media_migration_batch(JSONB, BOOLEAN) TO service_role;
