import { readFileSync, writeFileSync, readdirSync } from 'fs';
import { join } from 'path';
import { dirname } from 'path';
import { fileURLToPath } from 'url';
const __dirname = dirname(fileURLToPath(import.meta.url));
const TOOLS = join(__dirname, '..', 'tools');
const related = {};
for (const f of readdirSync(TOOLS).filter(n => n.startsWith('related_links_part') && n.endsWith('.json'))) {
  Object.assign(related, JSON.parse(readFileSync(join(TOOLS, f), 'utf8')));
}
const js = '// Auto-generated by tools/build_related_data.mjs from tools/related_links_part*.json\n' +
  '// Contextual internal links used by BlogPostLayout (React-rendered posts).\n' +
  'export const relatedPosts = ' + JSON.stringify(related, null, 2) + ';\n';
const dest = join(__dirname, '..', 'Apps', 'web', 'src', 'data', 'relatedPosts.js');
writeFileSync(dest, js);
console.log('Wrote', dest, Object.keys(related).length, 'entries');