import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import Header from "@/components/Header.jsx";
import Footer from "@/components/Footer.jsx";
import { useAuth } from "@/contexts/AuthContext.jsx";
import supabase from "@/lib/supabaseClient";

const money = new Intl.NumberFormat("en-NG", { style: "currency", currency: "NGN", maximumFractionDigits: 0 });

export default function ConsultantPortalPage() {
  const { currentUser, logout } = useAuth();
  const [email, setEmail] = useState(""); const [sent, setSent] = useState(false); const [data, setData] = useState(null); const [error, setError] = useState("");
  useEffect(() => { if (currentUser) supabase.functions.invoke("consultant-dashboard").then(({ data: result, error: invokeError }) => { if (invokeError || !result?.success) setError(result?.error || "Your consultant profile could not be found."); else setData(result.data); }); }, [currentUser]);
  async function sendLink(event) { event.preventDefault(); setError(""); const { error: otpError } = await supabase.auth.signInWithOtp({ email, options: { emailRedirectTo: `${window.location.origin}/consultant-portal` } }); if (otpError) setError(otpError.message); else setSent(true); }
  return <><Header /><main className="min-h-screen bg-slate-50 py-12"><div className="mx-auto max-w-6xl px-4">{!currentUser ? <section className="mx-auto max-w-md rounded-xl bg-white p-7 shadow"><h1 className="text-2xl font-semibold">Consultant portal</h1><p className="mt-2 text-sm text-slate-600">Enter the email used for registration. We will email you a secure sign-in link.</p><form onSubmit={sendLink} className="mt-5 space-y-3"><input type="email" required value={email} onChange={(e) => setEmail(e.target.value)} className="w-full rounded border p-3" placeholder="you@example.com" /><button className="w-full rounded bg-primary p-3 font-semibold">Email my access link</button></form>{sent && <p className="mt-3 text-sm text-green-700">Check your email for the access link.</p>}{error && <p className="mt-3 text-sm text-red-700">{error}</p>}</section> : <>{error ? <p className="rounded bg-red-50 p-4 text-red-700">{error}</p> : !data ? <p>Loading your portal…</p> : <><div className="flex items-center justify-between"><div><p className="text-sm text-primary">Consultant portal</p><h1 className="text-3xl font-semibold">Welcome, {data.consultant.full_name}</h1><p className="mt-1 text-sm text-slate-600">Your referral code: <strong>{data.consultant.referral_code}</strong></p></div><button onClick={logout} className="text-sm underline">Log out</button></div><div className="mt-7 grid gap-4 sm:grid-cols-2 lg:grid-cols-4"><Stat label="Direct referrals" value={data.stats.directReferrals} /><Stat label="Total network" value={data.stats.totalNetwork} /><Stat label="Pending commission" value={money.format(data.stats.pendingCommission)} /><Stat label="Paid commission" value={money.format(data.stats.paidCommission)} /></div><div className="mt-8 grid gap-6 lg:grid-cols-2"><Panel title="Your direct referrals">{data.referrals.length ? data.referrals.map((item) => <p key={item.id} className="border-b py-3 text-sm">{item.full_name}<span className="float-right text-slate-500">{item.created_at.slice(0, 10)}</span></p>) : <p className="text-sm text-slate-500">No referrals yet.</p>}</Panel><Panel title="Properties your network sold">{data.deals.length ? data.deals.map((deal) => <p key={deal.id} className="border-b py-3 text-sm">{deal.property_name}<span className="float-right">{money.format(deal.deal_amount)}</span></p>) : <p className="text-sm text-slate-500">No completed referral deals yet.</p>}</Panel></div><Panel title="Available properties" className="mt-6"><Link to="/properties" className="text-sm font-semibold text-primary">Browse available properties →</Link></Panel></>}</>}</div></main><Footer /></>;
}
function Stat({ label, value }) { return <div className="rounded-xl bg-white p-5 shadow-sm"><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-2xl font-semibold">{value}</p></div>; }
function Panel({ title, children, className = "" }) { return <section className={`rounded-xl bg-white p-5 shadow-sm ${className}`}><h2 className="font-semibold">{title}</h2><div className="mt-3">{children}</div></section>; }
